name: Trigger auto deployment for account-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ graphql ]
    paths:
    - '**'
    - '.github/workflows/account-service-AutoDeployTrigger-68815c03-117d-4c46-95c9-560557afc611.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ACCOUNTSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACCOUNTSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACCOUNTSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: topicmodellingsocialabs.azurecr.io
          registryUsername: ${{ secrets.ACCOUNTSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACCOUNTSERVICE_REGISTRY_PASSWORD }}
          containerAppName: account-service
          resourceGroup: socialabs_service
          imageToBuild: topicmodellingsocialabs.azurecr.io/account-service:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


